### ISSUE TITLE
Consider always parsing output so info level lints can be displayed

### ISSUE THREAD

**Issue by seancorfield** [gerred/linter-kondo#4]
`clj-kondo` exists with a zero status if there are `:info` level lint results (and no `:error` or `:warning` results). It would be nice if `linter-kondo` always looked for `:info`, `:warning`, `:error` results, even when the exit status is zero, and then displayed those info level lint results, along with errors and warnings.

Not sure how Atom would annotate/highlight info items in the code though.

**Comment by aviflax** [comment]
> Not sure how Atom would annotate/highlight info items in the code though.

I recently enabled a clj-kondo linter that’s disabled by default, and just now I linted a file in my editor. Because clj-kondo found a warning, it exited with code 2, which caused the package to display both the warning and the info. So I captured it:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/141844/82514673-56573c00-9ae4-11ea-909f-7bf7b46c4407.png">

So, it looks like the package currently interprets the `info` messages as errors.

**Comment by seancorfield** [comment]
@aviflax I don't know why it is showing `info: Missing docstring` but the `Severity` is `Error` which means you have:
```
  :missing-docstring {:level :error}
```
And, yes, if you enable this linter with `:error` or `:warning` you will get the red or orange wiggly line and the report below.

If you set it to `:info` _you will not get any report_ from it.

**Comment by aviflax** [comment]
@seancorfield well, my config contains:

```edn
:linters {:missing-docstring {:level :info} …
```

and when I run `clj-kondo --lint src` from my terminal I get lines like:

```text
./src/md2c8e/cli.clj:38:1: info: Missing docstring.
```

so clj-kondo is definitely reporting these issues as `info` level.

I’d guess it’s the package that’s interpreting these `info` level issues as errors when it converts them into something that the base Linter package understands.

Ah, yup:

https://github.com/gerred/linter-kondo/blob/30cf569d44d26663c244b71dcdcca61101d8c905/index.js#L78-L80

**Comment by seancorfield** [comment]
Weird. When I set it to `:info`, it simply doesn't show up at all in Atom for me. Which is why I opened this issue. So there must be some other configuration issue at play here.

**Comment by aviflax** [comment]
It’s because I _also_ had a `warning` which caused `clj-kondo` to exit with code `2` which caused the package to parse its output and feed it back to `linter`. So if you lint a file that has triggers _only_ `info` messages, they won’t then show up in the editor, because in that case `clj-kondo` exits with code 0.

Sorry I didn’t make that clear at first.

**Comment by seancorfield** [comment]
Just FYI: I no longer use Atom so this issue is moot for me. I'll leave it up to you whether to implement or just close but I'm going to unsubscribe from updates (you can still @ me I think if needed).

**Comment by seancorfield** [comment]
Closing due to lack of feedback/interest.
